root: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint', prettier]
extends: [eslint:recommended, 'plugin:@typescript-eslint/recommended', plugin:prettier/recommended]
rules:
  quotes: 'off'
  '@typescript-eslint/quotes': [error, single]
  semi: error
  curly: [error, all]
  '@typescript-eslint/semi': error
  '@typescript-eslint/explicit-member-accessibility': error
env:
  node: true
  es2020: true
  jest: true
